SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (1, N'Ежедневные расходы')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (3, N'Еда')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (4, N'Стрижка')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (5, N'Лекарства')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (6, N'Контактные линзы')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (7, N'Чай и кофе')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (8, N'Одежда')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (9, N'Химчистка')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (10, N'Косметика')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (11, N'Учеба')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (12, N'Сладости')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (13, N'Инструменты')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (14, N'Массаж')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (15, N'Жилье')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (16, N'Аренда')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (17, N'Ипотека')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (18, N'Бензин')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (19, N'Стационарный телефон')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (20, N'Интернет')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (21, N'Мобильный телефон')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (22, N'Вода')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (23, N'Электричество')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (24, N'Страховка')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (25, N'Медицинская страховка')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (26, N'Кредитные карты')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (27, N'Техника')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (28, N'Ремонт')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (29, N'Транспорт')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (30, N'Автомобиль')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (31, N'Страховка автомобиля')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (32, N'Проездной на автобус')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (33, N'Проездной на метро')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (34, N'Бензин')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (35, N'Налог на автомобиль')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (36, N'Проезд в поезде')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (37, N'Ремонт автомобиля')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (38, N'Маршрутка')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (39, N'Трамвай')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (40, N'Скоростной')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (41, N'Развлечения')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (42, N'Кабельное телевидение')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (43, N'Кино')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (44, N'Клуб')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (45, N'Покупка DVD-дисков')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (46, N'Прокат DVD-дисков')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (47, N'Кафе и рестораны')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (48, N'Тренажерный зал')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (49, N'Журналы')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (50, N'Музыкальные диски')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (51, N'Уроки музыки')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (52, N'Спортивные мероприятия')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (53, N'Билет на концерт')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (54, N'Спортинвентарь')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (55, N'Бильярд')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (56, N'Подарок')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (57, N'Книга')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (58, N'Отдых')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (59, N'Долг')
SET IDENTITY_INSERT [dbo].[Categories] OFF
